apiVersion: apps/v1
kind: Deployment
metadata:
  name: eshop-web-deployment
spec:
  replicas: 3 # occur 3 pod
  selector:
    matchLabels:
      app: eshop-web
  template:
    metadata:
      labels:
        app: eshop-web
    spec:
      containers:
      - name: eshop-web-containers
        image: warisaa/eshopweb-k8s:v1.0
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service # this is a bridge - connect to each app-pod
metadata:
  name: eshop-web-service
spec:
  selector:
    app: eshop-web
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 3000 # exposed port
  type: LoadBalancer

